### ISSUE TITLE
Quirk with Cloudflare R2

### ISSUE THREAD

**Issue by petritoast** [litejs/s3#1]
Both endpoint URLs work with R2:

1. MY-ID.r2.cloudflarestorage.com
2. MY-BUCKET.MY-ID.r2.cloudflarestorage.com

But list says "Not Implemented" when I try without the bucket name in endpoint URL. One could use getObject on "bucket_name/" it returns an object that has all the objects within (in contents). Everything works fine with the second option.

Also, I am completely new to the S3 API, but delete returns "No Content" (204), but still deletes it successfully. Is this a bug or working as intended? How will one know if there was nothing there to delete from this status message?

P.S: Really like this simple library, was looking for something lightweight and without additional dep.

**Comment by lauriro** [comment]
You should specify the bucket in either the URL or the options, but not both.
Based on tests, the list method works with both approaches.

According to HTTP standards, all 2xx status codes indicate success.
Status 204 is common for DELETE requests, as there is nothing more to say.

At the same time DELETE method is idempotent, meaning you can send same request multiple times and the final state on server remains same as with single request.

Cloudflare/AWS/Backblaze APIs return status 204 for both DELETE requests, whether the file existed or not.
Google API returns `Error: The specified key does not exist.` when deleting non-existing file.
I think it is just something to keep in mind.

`204 No Content` response indicates that the file no longer exists, regardless of its prior state.
To check if the file existed, a separate status request is required.

**Comment by lauriro** [comment]
CF workers have S3 api implemented, no need for a module there:
https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
const object = await env.MY_BUCKET.get(key);

**Comment by lauriro** [comment]
Thank you for raising the issue, it did help to improve this library.
Default region auto and list without options do make usage simpler.

Both options seems to work and github workflow test against service providers live servers.

```javascript
import S3 from "../s3.js"
const r2 = new S3({
	accessId: env.R2_ID,
	secret: env.R2_SECRET,
	endpoint: "MY-BUCKET.ACCOUNT_ID.r2.cloudflarestorage.com",
})
console.log(await r2.list())
// returns object not xml string
// { name: 'MY-BUCKET', contents: [ ... ], isTruncated: 'false', prefix: '', maxKeys: 10, keyCount: 1 }


const r2b = new S3({
	accessId: env.R2_ID,
	secret: env.R2_SECRET,
	bucket: "MY-BUCKET",
	endpoint: "ACCOUNT_ID.r2.cloudflarestorage.com",
})
console.log(await r2b.list())
```

I needed this library for MIPS CPU that is limited to Node8 :/
